const COUNTRIES = [
  // Africa
  { code: "NG", dial: "+234", name: "Nigeria" },
  { code: "GH", dial: "+233", name: "Ghana" },
  { code: "KE", dial: "+254", name: "Kenya" },
  { code: "ZA", dial: "+27", name: "South Africa" },
  { code: "ET", dial: "+251", name: "Ethiopia" },
  { code: "TZ", dial: "+255", name: "Tanzania" },
  { code: "UG", dial: "+256", name: "Uganda" },
  { code: "SN", dial: "+221", name: "Senegal" },
  { code: "CI", dial: "+225", name: "Côte d'Ivoire" },
  { code: "CM", dial: "+237", name: "Cameroon" },
  { code: "EG", dial: "+20", name: "Egypt" },
  { code: "MA", dial: "+212", name: "Morocco" },
  { code: "TN", dial: "+216", name: "Tunisia" },
  { code: "DZ", dial: "+213", name: "Algeria" },
  { code: "LY", dial: "+218", name: "Libya" },
  { code: "SD", dial: "+249", name: "Sudan" },
  { code: "AO", dial: "+244", name: "Angola" },
  { code: "MZ", dial: "+258", name: "Mozambique" },
  { code: "ZM", dial: "+260", name: "Zambia" },
  { code: "ZW", dial: "+263", name: "Zimbabwe" },
  { code: "RW", dial: "+250", name: "Rwanda" },
  { code: "BJ", dial: "+229", name: "Benin" },
  { code: "TG", dial: "+228", name: "Togo" },
  { code: "ML", dial: "+223", name: "Mali" },
  { code: "BF", dial: "+226", name: "Burkina Faso" },
  { code: "NE", dial: "+227", name: "Niger" },
  { code: "TD", dial: "+235", name: "Chad" },
  { code: "SO", dial: "+252", name: "Somalia" },
  { code: "MG", dial: "+261", name: "Madagascar" },
  { code: "CG", dial: "+242", name: "Congo" },
  { code: "CD", dial: "+243", name: "DR Congo" },
  { code: "GA", dial: "+241", name: "Gabon" },
  { code: "LS", dial: "+266", name: "Lesotho" },
  { code: "BW", dial: "+267", name: "Botswana" },
  { code: "NA", dial: "+264", name: "Namibia" },
  { code: "SZ", dial: "+268", name: "Eswatini" },
  { code: "MU", dial: "+230", name: "Mauritius" },
  { code: "CV", dial: "+238", name: "Cape Verde" },
  { code: "SC", dial: "+248", name: "Seychelles" },
  { code: "GM", dial: "+220", name: "Gambia" },
  { code: "GW", dial: "+245", name: "Guinea-Bissau" },
  { code: "GN", dial: "+224", name: "Guinea" },
  { code: "SL", dial: "+232", name: "Sierra Leone" },
  { code: "LR", dial: "+231", name: "Liberia" },
  { code: "ER", dial: "+291", name: "Eritrea" },
  { code: "DJ", dial: "+253", name: "Djibouti" },
  { code: "KM", dial: "+269", name: "Comoros" },
  { code: "ST", dial: "+239", name: "São Tomé & Príncipe" },
  { code: "GQ", dial: "+240", name: "Equatorial Guinea" },
  { code: "CF", dial: "+236", name: "Central African Republic" },
  { code: "BI", dial: "+257", name: "Burundi" },
  { code: "MW", dial: "+265", name: "Malawi" },
  { code: "SS", dial: "+211", name: "South Sudan" },
  { code: "MR", dial: "+222", name: "Mauritania" },
  { code: "EH", dial: "+212", name: "Western Sahara" },
  // Americas
  { code: "US", dial: "+1", name: "United States" },
  { code: "CA", dial: "+1", name: "Canada" },
  { code: "MX", dial: "+52", name: "Mexico" },
  { code: "BR", dial: "+55", name: "Brazil" },
  { code: "AR", dial: "+54", name: "Argentina" },
  { code: "CO", dial: "+57", name: "Colombia" },
  { code: "CL", dial: "+56", name: "Chile" },
  { code: "PE", dial: "+51", name: "Peru" },
  { code: "VE", dial: "+58", name: "Venezuela" },
  { code: "EC", dial: "+593", name: "Ecuador" },
  { code: "BO", dial: "+591", name: "Bolivia" },
  { code: "PY", dial: "+595", name: "Paraguay" },
  { code: "UY", dial: "+598", name: "Uruguay" },
  { code: "GT", dial: "+502", name: "Guatemala" },
  { code: "HN", dial: "+504", name: "Honduras" },
  { code: "SV", dial: "+503", name: "El Salvador" },
  { code: "NI", dial: "+505", name: "Nicaragua" },
  { code: "CR", dial: "+506", name: "Costa Rica" },
  { code: "PA", dial: "+507", name: "Panama" },
  { code: "CU", dial: "+53", name: "Cuba" },
  { code: "DO", dial: "+1-809", name: "Dominican Republic" },
  { code: "HT", dial: "+509", name: "Haiti" },
  { code: "JM", dial: "+1-876", name: "Jamaica" },
  { code: "TT", dial: "+1-868", name: "Trinidad & Tobago" },
  { code: "BB", dial: "+1-246", name: "Barbados" },
  { code: "BS", dial: "+1-242", name: "Bahamas" },
  { code: "GY", dial: "+592", name: "Guyana" },
  { code: "SR", dial: "+597", name: "Suriname" },
  { code: "BZ", dial: "+501", name: "Belize" },
  { code: "LC", dial: "+1-758", name: "Saint Lucia" },
  { code: "VC", dial: "+1-784", name: "Saint Vincent & Grenadines" },
  { code: "AG", dial: "+1-268", name: "Antigua & Barbuda" },
  { code: "DM", dial: "+1-767", name: "Dominica" },
  { code: "GD", dial: "+1-473", name: "Grenada" },
  { code: "KN", dial: "+1-869", name: "Saint Kitts & Nevis" },
  { code: "PR", dial: "+1-787", name: "Puerto Rico" },
  // Europe
  { code: "GB", dial: "+44", name: "United Kingdom" },
  { code: "FR", dial: "+33", name: "France" },
  { code: "DE", dial: "+49", name: "Germany" },
  { code: "IT", dial: "+39", name: "Italy" },
  { code: "ES", dial: "+34", name: "Spain" },
  { code: "PT", dial: "+351", name: "Portugal" },
  { code: "NL", dial: "+31", name: "Netherlands" },
  { code: "BE", dial: "+32", name: "Belgium" },
  { code: "SE", dial: "+46", name: "Sweden" },
  { code: "NO", dial: "+47", name: "Norway" },
  { code: "DK", dial: "+45", name: "Denmark" },
  { code: "FI", dial: "+358", name: "Finland" },
  { code: "PL", dial: "+48", name: "Poland" },
  { code: "UA", dial: "+380", name: "Ukraine" },
  { code: "RU", dial: "+7", name: "Russia" },
  { code: "TR", dial: "+90", name: "Turkey" },
  { code: "GR", dial: "+30", name: "Greece" },
  { code: "CZ", dial: "+420", name: "Czech Republic" },
  { code: "RO", dial: "+40", name: "Romania" },
  { code: "HU", dial: "+36", name: "Hungary" },
  { code: "AT", dial: "+43", name: "Austria" },
  { code: "CH", dial: "+41", name: "Switzerland" },
  { code: "SK", dial: "+421", name: "Slovakia" },
  { code: "BG", dial: "+359", name: "Bulgaria" },
  { code: "HR", dial: "+385", name: "Croatia" },
  { code: "RS", dial: "+381", name: "Serbia" },
  { code: "IE", dial: "+353", name: "Ireland" },
  { code: "LT", dial: "+370", name: "Lithuania" },
  { code: "LV", dial: "+371", name: "Latvia" },
  { code: "EE", dial: "+372", name: "Estonia" },
  { code: "SI", dial: "+386", name: "Slovenia" },
  { code: "BA", dial: "+387", name: "Bosnia & Herzegovina" },
  { code: "MK", dial: "+389", name: "North Macedonia" },
  { code: "AL", dial: "+355", name: "Albania" },
  { code: "ME", dial: "+382", name: "Montenegro" },
  { code: "IS", dial: "+354", name: "Iceland" },
  { code: "LU", dial: "+352", name: "Luxembourg" },
  { code: "MT", dial: "+356", name: "Malta" },
  { code: "CY", dial: "+357", name: "Cyprus" },
  { code: "MD", dial: "+373", name: "Moldova" },
  { code: "GE", dial: "+995", name: "Georgia" },
  { code: "AM", dial: "+374", name: "Armenia" },
  { code: "AZ", dial: "+994", name: "Azerbaijan" },
  { code: "BY", dial: "+375", name: "Belarus" },
  // Asia & Middle East
  { code: "IN", dial: "+91", name: "India" },
  { code: "PK", dial: "+92", name: "Pakistan" },
  { code: "BD", dial: "+880", name: "Bangladesh" },
  { code: "LK", dial: "+94", name: "Sri Lanka" },
  { code: "NP", dial: "+977", name: "Nepal" },
  { code: "MM", dial: "+95", name: "Myanmar" },
  { code: "AF", dial: "+93", name: "Afghanistan" },
  { code: "PH", dial: "+63", name: "Philippines" },
  { code: "ID", dial: "+62", name: "Indonesia" },
  { code: "MY", dial: "+60", name: "Malaysia" },
  { code: "SG", dial: "+65", name: "Singapore" },
  { code: "TH", dial: "+66", name: "Thailand" },
  { code: "VN", dial: "+84", name: "Vietnam" },
  { code: "CN", dial: "+86", name: "China" },
  { code: "JP", dial: "+81", name: "Japan" },
  { code: "KR", dial: "+82", name: "South Korea" },
  { code: "KH", dial: "+855", name: "Cambodia" },
  { code: "LA", dial: "+856", name: "Laos" },
  { code: "MN", dial: "+976", name: "Mongolia" },
  { code: "BT", dial: "+975", name: "Bhutan" },
  { code: "MV", dial: "+960", name: "Maldives" },
  { code: "TL", dial: "+670", name: "Timor-Leste" },
  { code: "BN", dial: "+673", name: "Brunei" },
  { code: "SA", dial: "+966", name: "Saudi Arabia" },
  { code: "AE", dial: "+971", name: "UAE" },
  { code: "QA", dial: "+974", name: "Qatar" },
  { code: "KW", dial: "+965", name: "Kuwait" },
  { code: "BH", dial: "+973", name: "Bahrain" },
  { code: "OM", dial: "+968", name: "Oman" },
  { code: "IQ", dial: "+964", name: "Iraq" },
  { code: "IR", dial: "+98", name: "Iran" },
  { code: "IL", dial: "+972", name: "Israel" },
  { code: "JO", dial: "+962", name: "Jordan" },
  { code: "LB", dial: "+961", name: "Lebanon" },
  { code: "SY", dial: "+963", name: "Syria" },
  { code: "YE", dial: "+967", name: "Yemen" },
  { code: "PS", dial: "+970", name: "Palestine" },
  { code: "KZ", dial: "+7", name: "Kazakhstan" },
  { code: "UZ", dial: "+998", name: "Uzbekistan" },
  { code: "TM", dial: "+993", name: "Turkmenistan" },
  { code: "TJ", dial: "+992", name: "Tajikistan" },
  { code: "KG", dial: "+996", name: "Kyrgyzstan" },
  // Oceania
  { code: "AU", dial: "+61", name: "Australia" },
  { code: "NZ", dial: "+64", name: "New Zealand" },
  { code: "FJ", dial: "+679", name: "Fiji" },
  { code: "PG", dial: "+675", name: "Papua New Guinea" },
  { code: "WS", dial: "+685", name: "Samoa" },
  { code: "TO", dial: "+676", name: "Tonga" },
  { code: "VU", dial: "+678", name: "Vanuatu" },
  { code: "SB", dial: "+677", name: "Solomon Islands" },
];

export default COUNTRIES;
