const COUNTRIES = [
  { code: "NG", dial: "+234", name: "Nigeria" },
  { code: "GH", dial: "+233", name: "Ghana" },
  { code: "KE", dial: "+254", name: "Kenya" },
  { code: "ZA", dial: "+27", name: "South Africa" },
  { code: "ET", dial: "+251", name: "Ethiopia" },
  { code: "TZ", dial: "+255", name: "Tanzania" },
  { code: "UG", dial: "+256", name: "Uganda" },
  { code: "SN", dial: "+221", name: "Senegal" },
  { code: "CI", dial: "+225", name: "Côte d'Ivoire" },
  { code: "CM", dial: "+237", name: "Cameroon" },
  { code: "EG", dial: "+20", name: "Egypt" },
  { code: "MA", dial: "+212", name: "Morocco" },
  { code: "TN", dial: "+216", name: "Tunisia" },
  { code: "DZ", dial: "+213", name: "Algeria" },
  { code: "LY", dial: "+218", name: "Libya" },
  { code: "SD", dial: "+249", name: "Sudan" },
  { code: "AO", dial: "+244", name: "Angola" },
  { code: "MZ", dial: "+258", name: "Mozambique" },
  { code: "ZM", dial: "+260", name: "Zambia" },
  { code: "ZW", dial: "+263", name: "Zimbabwe" },
  { code: "RW", dial: "+250", name: "Rwanda" },
  { code: "BJ", dial: "+229", name: "Benin" },
  { code: "TG", dial: "+228", name: "Togo" },
  { code: "ML", dial: "+223", name: "Mali" },
  { code: "BF", dial: "+226", name: "Burkina Faso" },
  { code: "NE", dial: "+227", name: "Niger" },
  { code: "TD", dial: "+235", name: "Chad" },
  { code: "SO", dial: "+252", name: "Somalia" },
  { code: "MG", dial: "+261", name: "Madagascar" },
  { code: "CG", dial: "+242", name: "Congo" },
  { code: "CD", dial: "+243", name: "DR Congo" },
  { code: "GA", dial: "+241", name: "Gabon" },
  { code: "LS", dial: "+266", name: "Lesotho" },
  { code: "BW", dial: "+267", name: "Botswana" },
  { code: "NA", dial: "+264", name: "Namibia" },
  { code: "SZ", dial: "+268", name: "Eswatini" },
  { code: "GB", dial: "+44", name: "United Kingdom" },
  { code: "US", dial: "+1", name: "United States" },
  { code: "CA", dial: "+1", name: "Canada" },
  { code: "IN", dial: "+91", name: "India" },
  { code: "PK", dial: "+92", name: "Pakistan" },
  { code: "BD", dial: "+880", name: "Bangladesh" },
  { code: "LK", dial: "+94", name: "Sri Lanka" },
  { code: "PH", dial: "+63", name: "Philippines" },
  { code: "ID", dial: "+62", name: "Indonesia" },
  { code: "MY", dial: "+60", name: "Malaysia" },
  { code: "SG", dial: "+65", name: "Singapore" },
  { code: "TH", dial: "+66", name: "Thailand" },
  { code: "VN", dial: "+84", name: "Vietnam" },
  { code: "CN", dial: "+86", name: "China" },
  { code: "JP", dial: "+81", name: "Japan" },
  { code: "KR", dial: "+82", name: "South Korea" },
  { code: "AU", dial: "+61", name: "Australia" },
  { code: "NZ", dial: "+64", name: "New Zealand" },
  { code: "FR", dial: "+33", name: "France" },
  { code: "DE", dial: "+49", name: "Germany" },
  { code: "IT", dial: "+39", name: "Italy" },
  { code: "ES", dial: "+34", name: "Spain" },
  { code: "PT", dial: "+351", name: "Portugal" },
  { code: "NL", dial: "+31", name: "Netherlands" },
  { code: "BE", dial: "+32", name: "Belgium" },
  { code: "SE", dial: "+46", name: "Sweden" },
  { code: "NO", dial: "+47", name: "Norway" },
  { code: "DK", dial: "+45", name: "Denmark" },
  { code: "FI", dial: "+358", name: "Finland" },
  { code: "PL", dial: "+48", name: "Poland" },
  { code: "UA", dial: "+380", name: "Ukraine" },
  { code: "RU", dial: "+7", name: "Russia" },
  { code: "TR", dial: "+90", name: "Turkey" },
  { code: "SA", dial: "+966", name: "Saudi Arabia" },
  { code: "AE", dial: "+971", name: "UAE" },
  { code: "QA", dial: "+974", name: "Qatar" },
  { code: "KW", dial: "+965", name: "Kuwait" },
  { code: "BH", dial: "+973", name: "Bahrain" },
  { code: "OM", dial: "+968", name: "Oman" },
  { code: "IQ", dial: "+964", name: "Iraq" },
  { code: "IR", dial: "+98", name: "Iran" },
  { code: "IL", dial: "+972", name: "Israel" },
  { code: "JO", dial: "+962", name: "Jordan" },
  { code: "LB", dial: "+961", name: "Lebanon" },
  { code: "BR", dial: "+55", name: "Brazil" },
  { code: "AR", dial: "+54", name: "Argentina" },
  { code: "CO", dial: "+57", name: "Colombia" },
  { code: "CL", dial: "+56", name: "Chile" },
  { code: "PE", dial: "+51", name: "Peru" },
  { code: "VE", dial: "+58", name: "Venezuela" },
  { code: "MX", dial: "+52", name: "Mexico" },
  { code: "GT", dial: "+502", name: "Guatemala" },
  { code: "CU", dial: "+53", name: "Cuba" },
  { code: "DO", dial: "+1", name: "Dominican Republic" },
  { code: "JM", dial: "+1", name: "Jamaica" },
  { code: "TT", dial: "+1", name: "Trinidad & Tobago" },
];

export default COUNTRIES;
